{{- define "containers.proxy" }}
- name: linkerd-proxy
  image: {{ .Values.Proxy.Image }}
  imagePullPolicy: IfNotPresent
  livenessProbe:
    httpGet:
      path: /metrics
      port: {{ .Values.Proxy.MetricsPort }}
    initialDelaySeconds: 10
  ports:
  - containerPort: {{ .Values.Ports.Inbound }}
    name: linkerd-proxy
  - containerPort: {{ .Values.Proxy.MetricsPort }}
    name: linkerd-metrics
  readinessProbe:
    httpGet:
      path: /metrics
      port: {{ .Values.Proxy.MetricsPort }}
    initialDelaySeconds: 10
  env:
    - name: LINKERD2_PROXY_LOG
      value: warn,linkerd2_proxy=info
    - name: LINKERD2_PROXY_BIND_TIMEOUT
      value: 10s
    - name: LINKERD2_PROXY_CONTROL_URL
      value: tcp://localhost.:{{ .Values.Ports.DestinationAPI }}
    - name: LINKERD2_PROXY_CONTROL_LISTENER
      value: tcp://0.0.0.0:{{ .Values.Proxy.ControlPort }}
    - name: LINKERD2_PROXY_METRICS_LISTENER
      value: tcp://0.0.0.0:{{ .Values.Proxy.MetricsPort }}
    - name: LINKERD2_PROXY_OUTBOUND_LISTENER
      value: tcp://127.0.0.1:{{ .Values.Ports.Outbound }}
    - name: LINKERD2_PROXY_INBOUND_LISTENER
      value: tcp://0.0.0.0:{{ .Values.Ports.Inbound }}
    - name: LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES
      value: .
    - name: LINKERD2_PROXY_POD_NAMESPACE
      value: {{ .Values.Namespace }}
  resources: {}
  securityContext:
    runAsUser: {{.Values.Proxy.UID}}
{{- end }}