{{- define "containers.proxy" }}
{{- $controlURL := printf "%s.%s.%s" "linkerd-destination" .root.Values.Namespace "svc.cluster.local" -}}
{{- if eq .name "tap" -}}
  {{- $controlURL = "localhost." }}
{{- end -}}
- name: linkerd-proxy
  image: {{ .root.Values.Proxy.Image }}
  imagePullPolicy: IfNotPresent
  livenessProbe:
    httpGet:
      path: /metrics
      port: {{ .root.Values.Proxy.MetricsPort }}
    initialDelaySeconds: 10
  ports:
  - containerPort: {{ .root.Values.Ports.Inbound }}
    name: linkerd-proxy
  - containerPort: {{ .root.Values.Proxy.MetricsPort }}
    name: linkerd-metrics
  readinessProbe:
    httpGet:
      path: /metrics
      port: {{ .root.Values.Proxy.MetricsPort }}
    initialDelaySeconds: 10
  env:
    - name: LINKERD2_PROXY_LOG
      value: {{ .root.Values.Proxy.LogLevel }}
    - name: LINKERD2_PROXY_BIND_TIMEOUT
      value: 10s
    - name: LINKERD2_PROXY_CONTROL_URL
      value: tcp://{{ $controlURL }}:{{ .root.Values.Ports.DestinationAPI }}
    - name: LINKERD2_PROXY_CONTROL_LISTENER
      value: tcp://0.0.0.0:{{ .root.Values.Proxy.ControlPort }}
    - name: LINKERD2_PROXY_METRICS_LISTENER
      value: tcp://0.0.0.0:{{ .root.Values.Proxy.MetricsPort }}
    - name: LINKERD2_PROXY_OUTBOUND_LISTENER
      value: tcp://127.0.0.1:{{ .root.Values.Ports.Outbound }}
    - name: LINKERD2_PROXY_INBOUND_LISTENER
      value: tcp://0.0.0.0:{{ .root.Values.Ports.Inbound }}
    - name: LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES
      value: .
    - name: LINKERD2_PROXY_POD_NAMESPACE
      value: {{ .root.Values.Namespace }}
  resources: {}
  securityContext:
    runAsUser: {{.root.Values.Proxy.UID}}
{{- end }}
