---
###
### Web
###
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-web
  namespace: {{.Values.Namespace}}
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-web
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: web
  annotations:
    {{.Values.CreatedByAnnotation}}: {{.Values.CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.Values.ControllerComponentLabel}}: web
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  - name: admin-http
    port: 9994
    targetPort: 9994
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: linkerd-web
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: web
  annotations:
    {{.Values.CreatedByAnnotation}}: {{.Values.CliVersion}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{.Values.ControllerComponentLabel}}: web
      annotations:
        {{.Values.CreatedByAnnotation}}: {{.Values.CliVersion}}
    spec:
      containers:
      - name: web
        ports:
        - name: http
          containerPort: 8084
        - name: admin-http
          containerPort: 9994
        image: {{.Values.WebImage}}
        imagePullPolicy: {{.Values.ImagePullPolicy}}
        args:
        - "-api-addr=linkerd-controller-api.{{.Values.Namespace}}.svc.cluster.local:8085"
        - "-grafana-addr=linkerd-grafana.{{.Values.Namespace}}.svc.cluster.local:3000"
        - "-uuid={{.Values.UUID}}"
        - "-controller-namespace={{.Values.Namespace}}"
        - "-log-level={{.Values.ControllerLogLevel}}"
        livenessProbe:
          httpGet:
            path: /ping
            port: 9994
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 9994
          failureThreshold: 7
        {{- if .Values.EnableHA }}
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
        {{- end }}
        securityContext:
          runAsUser: {{.Values.ControllerUID}}
      - name: linkerd-proxy
        image: {{ .Values.ProxyImage }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /metrics
            port: {{ .Values.ProxyMetricsPort }}
          initialDelaySeconds: 10
        ports:
        - containerPort: {{ .Values.InboundPort }}
          name: linkerd-proxy
        - containerPort: {{ .Values.ProxyMetricsPort }}
          name: linkerd-metrics
        readinessProbe:
          httpGet:
            path: /metrics
            port: {{ .Values.ProxyMetricsPort }}
          initialDelaySeconds: 10
        env:
          - name: LINKERD2_PROXY_LOG
            value: warn,linkerd2_proxy=info
          - name: LINKERD2_PROXY_BIND_TIMEOUT
            value: 10s
          - name: LINKERD2_PROXY_CONTROL_URL
            value: tcp://localhost.:{{ .Values.DestinationAPIPort }}
          - name: LINKERD2_PROXY_CONTROL_LISTENER
            value: tcp://0.0.0.0:{{ .Values.ProxyControlPort }}
          - name: LINKERD2_PROXY_METRICS_LISTENER
            value: tcp://0.0.0.0:{{ .Values.ProxyMetricsPort }}
          - name: LINKERD2_PROXY_OUTBOUND_LISTENER
            value: tcp://127.0.0.1:{{ .Values.OutboundPort }}
          - name: LINKERD2_PROXY_INBOUND_LISTENER
            value: tcp://0.0.0.0:{{ .Values.InboundPort }}
          - name: LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES
            value: .
          - name: LINKERD2_PROXY_POD_NAMESPACE
            value: {{ .Values.Namespace }}
        resources: {}
        securityContext:
          runAsUser: {{.Values.ProxyUID}}
        terminationMessagePolicy: FallbackToLogsOnError
      initContainers:
      - name: linkerd-init
        args:
        - --incoming-proxy-port
        - "{{ .Values.InboundPort }}"
        - --outgoing-proxy-port
        - "{{ .Values.OutboundPort }}"
        - --proxy-uid
        - "{{ .Values.ProxyUID }}"
        - --inbound-ports-to-ignore
        - {{ .Values.IgnoreInboundPorts }}
        image: {{ .Values.ProxyInitImage }}
        imagePullPolicy: IfNotPresent
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
        terminationMessagePolicy: FallbackToLogsOnError
      serviceAccountName: linkerd-web
